// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShoeventoryAPI.Data;

#nullable disable

namespace ShoeventoryAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230802183316_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShoeventoryAPI.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShoeCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ShoeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShoeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ShoePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("ShoeQuantity")
                        .HasColumnType("integer");

                    b.Property<double>("ShoeSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ShoeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShoeCollectionId");

                    b.ToTable("Shoes");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.ShoeCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer");

                    b.Property<string>("ShoeCollectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("ShoeCollections");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.Shoe", b =>
                {
                    b.HasOne("ShoeventoryAPI.Models.ShoeCollection", "ShoeCollection")
                        .WithMany("Shoes")
                        .HasForeignKey("ShoeCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeCollection");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.ShoeCollection", b =>
                {
                    b.HasOne("ShoeventoryAPI.Models.Merchant", "Merchant")
                        .WithMany("ShoeCollections")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.Merchant", b =>
                {
                    b.Navigation("ShoeCollections");
                });

            modelBuilder.Entity("ShoeventoryAPI.Models.ShoeCollection", b =>
                {
                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
